//! Repo context scanning: git status, branch, recent diff.

use std::path::Path;
use std::process::Command;

use crate::error::DoreanError;

/// How much of the working-tree diff to include in the prompt.
const MAX_DIFF_CHARS: usize = 8_000;
/// How many status lines to include.
const MAX_STATUS_LINES: usize = 40;

/// A snapshot of the repository the agent operates in.
#[derive(Debug, Clone, Default)]
pub struct RepoContext {
    pub in_repo: bool,
    pub branch: Option<String>,
    pub is_clean: bool,
    /// `git status --short` lines (capped), plus an untracked-file summary.
    pub status: String,
    /// Recent working-tree diff (capped), as generated by `git diff`.
    pub diff: String,
    pub commit: Option<String>,
}

impl RepoContext {
    /// Snapshot the repo at `cwd`. Non-git directories yield a default
    /// context rather than an error.
    pub fn snapshot(cwd: &Path) -> RepoContext {
        if !Command::new("git")
            .arg("rev-parse")
            .arg("--is-inside-work-tree")
            .current_dir(cwd)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return RepoContext::default();
        }

        let branch = run(cwd, &["branch", "--show-current"]).ok().map(trim_ok);
        let commit = run(cwd, &["rev-parse", "--short", "HEAD"])
            .ok()
            .map(trim_ok);
        let status_raw = run(cwd, &["status", "--short"]).unwrap_or_default();
        let mut status_lines: Vec<&str> = status_raw.lines().collect();
        status_lines.truncate(MAX_STATUS_LINES);
        let status = status_lines.join("\n");
        let is_clean = status.is_empty();

        let diff = run(cwd, &["diff", "--stat", "--", ".", ":(exclude).dorean"])
            .map(|d| {
                let mut text = d;
                if text.len() > MAX_DIFF_CHARS {
                    text.truncate(MAX_DIFF_CHARS);
                    text.push_str("\n… diff truncated");
                }
                text
            })
            .unwrap_or_default();

        RepoContext {
            in_repo: true,
            branch,
            is_clean,
            status,
            diff,
            commit,
        }
    }

    /// A short human-readable summary for the CLI or the TUI status line.
    pub fn summary(&self) -> String {
        if !self.in_repo {
            return "(not a git repo)".to_string();
        }
        let branch = self
            .branch
            .clone()
            .unwrap_or_else(|| "(detached)".to_string());
        let commit = self.commit.clone().unwrap_or_default();
        let state = if self.is_clean { "clean" } else { "dirty" };
        format!("{branch} {commit} ({state})")
    }
}

fn run(cwd: &Path, args: &[&str]) -> Result<String, DoreanError> {
    let output = Command::new("git").args(args).current_dir(cwd).output()?;
    if !output.status.success() {
        return Err(DoreanError::Message(format!(
            "git {} failed",
            args.join(" ")
        )));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn trim_ok(s: String) -> String {
    s.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn temp_repo(tag: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("dorean-git-{tag}-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        Command::new("git")
            .args(["init", "-q", "-b", "main"])
            .current_dir(&dir)
            .status()
            .unwrap();
        Command::new("git")
            .args(["config", "user.email", "test@example.com"])
            .current_dir(&dir)
            .status()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "dorean test"])
            .current_dir(&dir)
            .status()
            .unwrap();
        dir
    }

    #[test]
    fn non_repo_directory_yields_default() {
        let ctx = RepoContext::snapshot(Path::new("/tmp"));
        assert!(!ctx.in_repo);
    }

    #[test]
    fn reports_branch_and_clean_state() {
        let dir = temp_repo("clean");
        fs::write(dir.join("a.txt"), "x").unwrap();
        let ctx = RepoContext::snapshot(&dir);
        assert!(ctx.in_repo);
        assert_eq!(ctx.branch.as_deref(), Some("main"));
        // Untracked files make the tree dirty.
        assert!(!ctx.is_clean);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn detects_dirty_tree_after_commit() {
        let dir = temp_repo("dirty");
        fs::write(dir.join("a.txt"), "x").unwrap();
        Command::new("git")
            .args(["add", "-A"])
            .current_dir(&dir)
            .status()
            .unwrap();
        Command::new("git")
            .args(["commit", "-q", "-m", "init"])
            .current_dir(&dir)
            .status()
            .unwrap();
        let ctx = RepoContext::snapshot(&dir);
        assert!(ctx.is_clean);

        fs::write(dir.join("a.txt"), "changed").unwrap();
        let dirty = RepoContext::snapshot(&dir);
        assert!(!dirty.is_clean);
        assert!(dirty.diff.contains("a.txt"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn summary_is_compact() {
        let dir = temp_repo("summary");
        let ctx = RepoContext::snapshot(&dir);
        let s = ctx.summary();
        assert!(s.contains("main"));
        let _ = fs::remove_dir_all(&dir);
    }
}
